//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.1.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class BeCliente {
    
    private ushort idClienteField;
    
    private ushort idUsuarioField;
    
    private string aliasField;
    
    private string emailAlternativoField;
    
    private bool tieneInfoCompletaField;
    
    private bool habilitarMonederoField;
    
    private System.DateTime fechaInfoCompletaField;
    
    private System.DateTime fechaHabilitarMonederoField;
    
    private System.DateTime fechaInhabilitarMonederoField;
    
    private string observacionesField;
    
    /// <comentarios/>
    public ushort IdCliente {
        get {
            return this.idClienteField;
        }
        set {
            this.idClienteField = value;
        }
    }
    
    /// <comentarios/>
    public ushort IdUsuario {
        get {
            return this.idUsuarioField;
        }
        set {
            this.idUsuarioField = value;
        }
    }
    
    /// <comentarios/>
    public string Alias {
        get {
            return this.aliasField;
        }
        set {
            this.aliasField = value;
        }
    }
    
    /// <comentarios/>
    public string EmailAlternativo {
        get {
            return this.emailAlternativoField;
        }
        set {
            this.emailAlternativoField = value;
        }
    }
    
    /// <comentarios/>
    public bool TieneInfoCompleta {
        get {
            return this.tieneInfoCompletaField;
        }
        set {
            this.tieneInfoCompletaField = value;
        }
    }
    
    /// <comentarios/>
    public bool HabilitarMonedero {
        get {
            return this.habilitarMonederoField;
        }
        set {
            this.habilitarMonederoField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime FechaInfoCompleta {
        get {
            return this.fechaInfoCompletaField;
        }
        set {
            this.fechaInfoCompletaField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime FechaHabilitarMonedero {
        get {
            return this.fechaHabilitarMonederoField;
        }
        set {
            this.fechaHabilitarMonederoField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime FechaInhabilitarMonedero {
        get {
            return this.fechaInhabilitarMonederoField;
        }
        set {
            this.fechaInhabilitarMonederoField = value;
        }
    }
    
    /// <comentarios/>
    public string Observaciones {
        get {
            return this.observacionesField;
        }
        set {
            this.observacionesField = value;
        }
    }
}
